// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report_message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_report_5fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_report_5fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_report_5fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_report_5fmessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_report_5fmessage_2eproto;
namespace lite_monitor {
class MonitorData;
struct MonitorDataDefaultTypeInternal;
extern MonitorDataDefaultTypeInternal _MonitorData_default_instance_;
class ReportMessage;
struct ReportMessageDefaultTypeInternal;
extern ReportMessageDefaultTypeInternal _ReportMessage_default_instance_;
}  // namespace lite_monitor
PROTOBUF_NAMESPACE_OPEN
template<> ::lite_monitor::MonitorData* Arena::CreateMaybeMessage<::lite_monitor::MonitorData>(Arena*);
template<> ::lite_monitor::ReportMessage* Arena::CreateMaybeMessage<::lite_monitor::ReportMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace lite_monitor {

// ===================================================================

class MonitorData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lite_monitor.MonitorData) */ {
 public:
  inline MonitorData() : MonitorData(nullptr) {}
  ~MonitorData() override;
  explicit PROTOBUF_CONSTEXPR MonitorData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MonitorData(const MonitorData& from);
  MonitorData(MonitorData&& from) noexcept
    : MonitorData() {
    *this = ::std::move(from);
  }

  inline MonitorData& operator=(const MonitorData& from) {
    CopyFrom(from);
    return *this;
  }
  inline MonitorData& operator=(MonitorData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MonitorData& default_instance() {
    return *internal_default_instance();
  }
  enum ValueCase {
    kStringValue = 4,
    kIntValue = 5,
    kDoubleValue = 6,
    VALUE_NOT_SET = 0,
  };

  static inline const MonitorData* internal_default_instance() {
    return reinterpret_cast<const MonitorData*>(
               &_MonitorData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MonitorData& a, MonitorData& b) {
    a.Swap(&b);
  }
  inline void Swap(MonitorData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MonitorData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MonitorData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MonitorData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MonitorData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MonitorData& from) {
    MonitorData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MonitorData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lite_monitor.MonitorData";
  }
  protected:
  explicit MonitorData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemFieldNumber = 3,
    kTimestampFieldNumber = 7,
    kIdFieldNumber = 1,
    kStringValueFieldNumber = 4,
    kIntValueFieldNumber = 5,
    kDoubleValueFieldNumber = 6,
  };
  // string item = 3;
  void clear_item();
  const std::string& item() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_item(ArgT0&& arg0, ArgT... args);
  std::string* mutable_item();
  PROTOBUF_NODISCARD std::string* release_item();
  void set_allocated_item(std::string* item);
  private:
  const std::string& _internal_item() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_item(const std::string& value);
  std::string* _internal_mutable_item();
  public:

  // int64 timestamp = 7;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // string string_value = 4;
  bool has_string_value() const;
  private:
  bool _internal_has_string_value() const;
  public:
  void clear_string_value();
  const std::string& string_value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_string_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_string_value();
  PROTOBUF_NODISCARD std::string* release_string_value();
  void set_allocated_string_value(std::string* string_value);
  private:
  const std::string& _internal_string_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_string_value(const std::string& value);
  std::string* _internal_mutable_string_value();
  public:

  // int64 int_value = 5;
  bool has_int_value() const;
  private:
  bool _internal_has_int_value() const;
  public:
  void clear_int_value();
  int64_t int_value() const;
  void set_int_value(int64_t value);
  private:
  int64_t _internal_int_value() const;
  void _internal_set_int_value(int64_t value);
  public:

  // double double_value = 6;
  bool has_double_value() const;
  private:
  bool _internal_has_double_value() const;
  public:
  void clear_double_value();
  double double_value() const;
  void set_double_value(double value);
  private:
  double _internal_double_value() const;
  void _internal_set_double_value(double value);
  public:

  void clear_value();
  ValueCase value_case() const;
  // @@protoc_insertion_point(class_scope:lite_monitor.MonitorData)
 private:
  class _Internal;
  void set_has_string_value();
  void set_has_int_value();
  void set_has_double_value();

  inline bool has_value() const;
  inline void clear_has_value();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr item_;
    int64_t timestamp_;
    int32_t id_;
    union ValueUnion {
      constexpr ValueUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr string_value_;
      int64_t int_value_;
      double double_value_;
    } value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_report_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class ReportMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lite_monitor.ReportMessage) */ {
 public:
  inline ReportMessage() : ReportMessage(nullptr) {}
  ~ReportMessage() override;
  explicit PROTOBUF_CONSTEXPR ReportMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReportMessage(const ReportMessage& from);
  ReportMessage(ReportMessage&& from) noexcept
    : ReportMessage() {
    *this = ::std::move(from);
  }

  inline ReportMessage& operator=(const ReportMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReportMessage& operator=(ReportMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReportMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReportMessage* internal_default_instance() {
    return reinterpret_cast<const ReportMessage*>(
               &_ReportMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ReportMessage& a, ReportMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ReportMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReportMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReportMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReportMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReportMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReportMessage& from) {
    ReportMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReportMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lite_monitor.ReportMessage";
  }
  protected:
  explicit ReportMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 3,
    kMessageTypeFieldNumber = 1,
    kHostFieldNumber = 2,
  };
  // repeated .lite_monitor.MonitorData data = 3;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  ::lite_monitor::MonitorData* mutable_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lite_monitor::MonitorData >*
      mutable_data();
  private:
  const ::lite_monitor::MonitorData& _internal_data(int index) const;
  ::lite_monitor::MonitorData* _internal_add_data();
  public:
  const ::lite_monitor::MonitorData& data(int index) const;
  ::lite_monitor::MonitorData* add_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lite_monitor::MonitorData >&
      data() const;

  // string message_type = 1;
  void clear_message_type();
  const std::string& message_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message_type();
  PROTOBUF_NODISCARD std::string* release_message_type();
  void set_allocated_message_type(std::string* message_type);
  private:
  const std::string& _internal_message_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message_type(const std::string& value);
  std::string* _internal_mutable_message_type();
  public:

  // string host = 2;
  void clear_host();
  const std::string& host() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_host(ArgT0&& arg0, ArgT... args);
  std::string* mutable_host();
  PROTOBUF_NODISCARD std::string* release_host();
  void set_allocated_host(std::string* host);
  private:
  const std::string& _internal_host() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_host(const std::string& value);
  std::string* _internal_mutable_host();
  public:

  // @@protoc_insertion_point(class_scope:lite_monitor.ReportMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lite_monitor::MonitorData > data_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr host_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_report_5fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MonitorData

// int32 id = 1;
inline void MonitorData::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t MonitorData::_internal_id() const {
  return _impl_.id_;
}
inline int32_t MonitorData::id() const {
  // @@protoc_insertion_point(field_get:lite_monitor.MonitorData.id)
  return _internal_id();
}
inline void MonitorData::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void MonitorData::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:lite_monitor.MonitorData.id)
}

// string item = 3;
inline void MonitorData::clear_item() {
  _impl_.item_.ClearToEmpty();
}
inline const std::string& MonitorData::item() const {
  // @@protoc_insertion_point(field_get:lite_monitor.MonitorData.item)
  return _internal_item();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MonitorData::set_item(ArgT0&& arg0, ArgT... args) {
 
 _impl_.item_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lite_monitor.MonitorData.item)
}
inline std::string* MonitorData::mutable_item() {
  std::string* _s = _internal_mutable_item();
  // @@protoc_insertion_point(field_mutable:lite_monitor.MonitorData.item)
  return _s;
}
inline const std::string& MonitorData::_internal_item() const {
  return _impl_.item_.Get();
}
inline void MonitorData::_internal_set_item(const std::string& value) {
  
  _impl_.item_.Set(value, GetArenaForAllocation());
}
inline std::string* MonitorData::_internal_mutable_item() {
  
  return _impl_.item_.Mutable(GetArenaForAllocation());
}
inline std::string* MonitorData::release_item() {
  // @@protoc_insertion_point(field_release:lite_monitor.MonitorData.item)
  return _impl_.item_.Release();
}
inline void MonitorData::set_allocated_item(std::string* item) {
  if (item != nullptr) {
    
  } else {
    
  }
  _impl_.item_.SetAllocated(item, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.item_.IsDefault()) {
    _impl_.item_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lite_monitor.MonitorData.item)
}

// string string_value = 4;
inline bool MonitorData::_internal_has_string_value() const {
  return value_case() == kStringValue;
}
inline bool MonitorData::has_string_value() const {
  return _internal_has_string_value();
}
inline void MonitorData::set_has_string_value() {
  _impl_._oneof_case_[0] = kStringValue;
}
inline void MonitorData::clear_string_value() {
  if (_internal_has_string_value()) {
    _impl_.value_.string_value_.Destroy();
    clear_has_value();
  }
}
inline const std::string& MonitorData::string_value() const {
  // @@protoc_insertion_point(field_get:lite_monitor.MonitorData.string_value)
  return _internal_string_value();
}
template <typename ArgT0, typename... ArgT>
inline void MonitorData::set_string_value(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_string_value()) {
    clear_value();
    set_has_string_value();
    _impl_.value_.string_value_.InitDefault();
  }
  _impl_.value_.string_value_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lite_monitor.MonitorData.string_value)
}
inline std::string* MonitorData::mutable_string_value() {
  std::string* _s = _internal_mutable_string_value();
  // @@protoc_insertion_point(field_mutable:lite_monitor.MonitorData.string_value)
  return _s;
}
inline const std::string& MonitorData::_internal_string_value() const {
  if (_internal_has_string_value()) {
    return _impl_.value_.string_value_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void MonitorData::_internal_set_string_value(const std::string& value) {
  if (!_internal_has_string_value()) {
    clear_value();
    set_has_string_value();
    _impl_.value_.string_value_.InitDefault();
  }
  _impl_.value_.string_value_.Set(value, GetArenaForAllocation());
}
inline std::string* MonitorData::_internal_mutable_string_value() {
  if (!_internal_has_string_value()) {
    clear_value();
    set_has_string_value();
    _impl_.value_.string_value_.InitDefault();
  }
  return _impl_.value_.string_value_.Mutable(      GetArenaForAllocation());
}
inline std::string* MonitorData::release_string_value() {
  // @@protoc_insertion_point(field_release:lite_monitor.MonitorData.string_value)
  if (_internal_has_string_value()) {
    clear_has_value();
    return _impl_.value_.string_value_.Release();
  } else {
    return nullptr;
  }
}
inline void MonitorData::set_allocated_string_value(std::string* string_value) {
  if (has_value()) {
    clear_value();
  }
  if (string_value != nullptr) {
    set_has_string_value();
    _impl_.value_.string_value_.InitAllocated(string_value, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:lite_monitor.MonitorData.string_value)
}

// int64 int_value = 5;
inline bool MonitorData::_internal_has_int_value() const {
  return value_case() == kIntValue;
}
inline bool MonitorData::has_int_value() const {
  return _internal_has_int_value();
}
inline void MonitorData::set_has_int_value() {
  _impl_._oneof_case_[0] = kIntValue;
}
inline void MonitorData::clear_int_value() {
  if (_internal_has_int_value()) {
    _impl_.value_.int_value_ = int64_t{0};
    clear_has_value();
  }
}
inline int64_t MonitorData::_internal_int_value() const {
  if (_internal_has_int_value()) {
    return _impl_.value_.int_value_;
  }
  return int64_t{0};
}
inline void MonitorData::_internal_set_int_value(int64_t value) {
  if (!_internal_has_int_value()) {
    clear_value();
    set_has_int_value();
  }
  _impl_.value_.int_value_ = value;
}
inline int64_t MonitorData::int_value() const {
  // @@protoc_insertion_point(field_get:lite_monitor.MonitorData.int_value)
  return _internal_int_value();
}
inline void MonitorData::set_int_value(int64_t value) {
  _internal_set_int_value(value);
  // @@protoc_insertion_point(field_set:lite_monitor.MonitorData.int_value)
}

// double double_value = 6;
inline bool MonitorData::_internal_has_double_value() const {
  return value_case() == kDoubleValue;
}
inline bool MonitorData::has_double_value() const {
  return _internal_has_double_value();
}
inline void MonitorData::set_has_double_value() {
  _impl_._oneof_case_[0] = kDoubleValue;
}
inline void MonitorData::clear_double_value() {
  if (_internal_has_double_value()) {
    _impl_.value_.double_value_ = 0;
    clear_has_value();
  }
}
inline double MonitorData::_internal_double_value() const {
  if (_internal_has_double_value()) {
    return _impl_.value_.double_value_;
  }
  return 0;
}
inline void MonitorData::_internal_set_double_value(double value) {
  if (!_internal_has_double_value()) {
    clear_value();
    set_has_double_value();
  }
  _impl_.value_.double_value_ = value;
}
inline double MonitorData::double_value() const {
  // @@protoc_insertion_point(field_get:lite_monitor.MonitorData.double_value)
  return _internal_double_value();
}
inline void MonitorData::set_double_value(double value) {
  _internal_set_double_value(value);
  // @@protoc_insertion_point(field_set:lite_monitor.MonitorData.double_value)
}

// int64 timestamp = 7;
inline void MonitorData::clear_timestamp() {
  _impl_.timestamp_ = int64_t{0};
}
inline int64_t MonitorData::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline int64_t MonitorData::timestamp() const {
  // @@protoc_insertion_point(field_get:lite_monitor.MonitorData.timestamp)
  return _internal_timestamp();
}
inline void MonitorData::_internal_set_timestamp(int64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void MonitorData::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:lite_monitor.MonitorData.timestamp)
}

inline bool MonitorData::has_value() const {
  return value_case() != VALUE_NOT_SET;
}
inline void MonitorData::clear_has_value() {
  _impl_._oneof_case_[0] = VALUE_NOT_SET;
}
inline MonitorData::ValueCase MonitorData::value_case() const {
  return MonitorData::ValueCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// ReportMessage

// string message_type = 1;
inline void ReportMessage::clear_message_type() {
  _impl_.message_type_.ClearToEmpty();
}
inline const std::string& ReportMessage::message_type() const {
  // @@protoc_insertion_point(field_get:lite_monitor.ReportMessage.message_type)
  return _internal_message_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReportMessage::set_message_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lite_monitor.ReportMessage.message_type)
}
inline std::string* ReportMessage::mutable_message_type() {
  std::string* _s = _internal_mutable_message_type();
  // @@protoc_insertion_point(field_mutable:lite_monitor.ReportMessage.message_type)
  return _s;
}
inline const std::string& ReportMessage::_internal_message_type() const {
  return _impl_.message_type_.Get();
}
inline void ReportMessage::_internal_set_message_type(const std::string& value) {
  
  _impl_.message_type_.Set(value, GetArenaForAllocation());
}
inline std::string* ReportMessage::_internal_mutable_message_type() {
  
  return _impl_.message_type_.Mutable(GetArenaForAllocation());
}
inline std::string* ReportMessage::release_message_type() {
  // @@protoc_insertion_point(field_release:lite_monitor.ReportMessage.message_type)
  return _impl_.message_type_.Release();
}
inline void ReportMessage::set_allocated_message_type(std::string* message_type) {
  if (message_type != nullptr) {
    
  } else {
    
  }
  _impl_.message_type_.SetAllocated(message_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_type_.IsDefault()) {
    _impl_.message_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lite_monitor.ReportMessage.message_type)
}

// string host = 2;
inline void ReportMessage::clear_host() {
  _impl_.host_.ClearToEmpty();
}
inline const std::string& ReportMessage::host() const {
  // @@protoc_insertion_point(field_get:lite_monitor.ReportMessage.host)
  return _internal_host();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReportMessage::set_host(ArgT0&& arg0, ArgT... args) {
 
 _impl_.host_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lite_monitor.ReportMessage.host)
}
inline std::string* ReportMessage::mutable_host() {
  std::string* _s = _internal_mutable_host();
  // @@protoc_insertion_point(field_mutable:lite_monitor.ReportMessage.host)
  return _s;
}
inline const std::string& ReportMessage::_internal_host() const {
  return _impl_.host_.Get();
}
inline void ReportMessage::_internal_set_host(const std::string& value) {
  
  _impl_.host_.Set(value, GetArenaForAllocation());
}
inline std::string* ReportMessage::_internal_mutable_host() {
  
  return _impl_.host_.Mutable(GetArenaForAllocation());
}
inline std::string* ReportMessage::release_host() {
  // @@protoc_insertion_point(field_release:lite_monitor.ReportMessage.host)
  return _impl_.host_.Release();
}
inline void ReportMessage::set_allocated_host(std::string* host) {
  if (host != nullptr) {
    
  } else {
    
  }
  _impl_.host_.SetAllocated(host, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.host_.IsDefault()) {
    _impl_.host_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lite_monitor.ReportMessage.host)
}

// repeated .lite_monitor.MonitorData data = 3;
inline int ReportMessage::_internal_data_size() const {
  return _impl_.data_.size();
}
inline int ReportMessage::data_size() const {
  return _internal_data_size();
}
inline void ReportMessage::clear_data() {
  _impl_.data_.Clear();
}
inline ::lite_monitor::MonitorData* ReportMessage::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:lite_monitor.ReportMessage.data)
  return _impl_.data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lite_monitor::MonitorData >*
ReportMessage::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:lite_monitor.ReportMessage.data)
  return &_impl_.data_;
}
inline const ::lite_monitor::MonitorData& ReportMessage::_internal_data(int index) const {
  return _impl_.data_.Get(index);
}
inline const ::lite_monitor::MonitorData& ReportMessage::data(int index) const {
  // @@protoc_insertion_point(field_get:lite_monitor.ReportMessage.data)
  return _internal_data(index);
}
inline ::lite_monitor::MonitorData* ReportMessage::_internal_add_data() {
  return _impl_.data_.Add();
}
inline ::lite_monitor::MonitorData* ReportMessage::add_data() {
  ::lite_monitor::MonitorData* _add = _internal_add_data();
  // @@protoc_insertion_point(field_add:lite_monitor.ReportMessage.data)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lite_monitor::MonitorData >&
ReportMessage::data() const {
  // @@protoc_insertion_point(field_list:lite_monitor.ReportMessage.data)
  return _impl_.data_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace lite_monitor

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_report_5fmessage_2eproto
