// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request_items.proto

#include "request_items.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace lite_monitor {
PROTOBUF_CONSTEXPR RequestItems::RequestItems(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.host_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RequestItemsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestItemsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestItemsDefaultTypeInternal() {}
  union {
    RequestItems _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestItemsDefaultTypeInternal _RequestItems_default_instance_;
}  // namespace lite_monitor
static ::_pb::Metadata file_level_metadata_request_5fitems_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_request_5fitems_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_request_5fitems_2eproto = nullptr;

const uint32_t TableStruct_request_5fitems_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::lite_monitor::RequestItems, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lite_monitor::RequestItems, _impl_.message_type_),
  PROTOBUF_FIELD_OFFSET(::lite_monitor::RequestItems, _impl_.host_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::lite_monitor::RequestItems)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::lite_monitor::_RequestItems_default_instance_._instance,
};

const char descriptor_table_protodef_request_5fitems_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023request_items.proto\022\014lite_monitor\"2\n\014R"
  "equestItems\022\024\n\014message_type\030\001 \001(\t\022\014\n\004hos"
  "t\030\002 \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_request_5fitems_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_request_5fitems_2eproto = {
    false, false, 95, descriptor_table_protodef_request_5fitems_2eproto,
    "request_items.proto",
    &descriptor_table_request_5fitems_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_request_5fitems_2eproto::offsets,
    file_level_metadata_request_5fitems_2eproto, file_level_enum_descriptors_request_5fitems_2eproto,
    file_level_service_descriptors_request_5fitems_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_request_5fitems_2eproto_getter() {
  return &descriptor_table_request_5fitems_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_request_5fitems_2eproto(&descriptor_table_request_5fitems_2eproto);
namespace lite_monitor {

// ===================================================================

class RequestItems::_Internal {
 public:
};

RequestItems::RequestItems(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:lite_monitor.RequestItems)
}
RequestItems::RequestItems(const RequestItems& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RequestItems* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_type_){}
    , decltype(_impl_.host_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message_type().empty()) {
    _this->_impl_.message_type_.Set(from._internal_message_type(), 
      _this->GetArenaForAllocation());
  }
  _impl_.host_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.host_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_host().empty()) {
    _this->_impl_.host_.Set(from._internal_host(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:lite_monitor.RequestItems)
}

inline void RequestItems::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_type_){}
    , decltype(_impl_.host_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.host_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.host_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RequestItems::~RequestItems() {
  // @@protoc_insertion_point(destructor:lite_monitor.RequestItems)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RequestItems::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_type_.Destroy();
  _impl_.host_.Destroy();
}

void RequestItems::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RequestItems::Clear() {
// @@protoc_insertion_point(message_clear_start:lite_monitor.RequestItems)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_type_.ClearToEmpty();
  _impl_.host_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RequestItems::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string message_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_message_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lite_monitor.RequestItems.message_type"));
        } else
          goto handle_unusual;
        continue;
      // string host = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_host();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lite_monitor.RequestItems.host"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RequestItems::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lite_monitor.RequestItems)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string message_type = 1;
  if (!this->_internal_message_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message_type().data(), static_cast<int>(this->_internal_message_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lite_monitor.RequestItems.message_type");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_message_type(), target);
  }

  // string host = 2;
  if (!this->_internal_host().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_host().data(), static_cast<int>(this->_internal_host().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lite_monitor.RequestItems.host");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_host(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lite_monitor.RequestItems)
  return target;
}

size_t RequestItems::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lite_monitor.RequestItems)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message_type = 1;
  if (!this->_internal_message_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message_type());
  }

  // string host = 2;
  if (!this->_internal_host().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_host());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RequestItems::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RequestItems::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RequestItems::GetClassData() const { return &_class_data_; }


void RequestItems::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RequestItems*>(&to_msg);
  auto& from = static_cast<const RequestItems&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lite_monitor.RequestItems)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message_type().empty()) {
    _this->_internal_set_message_type(from._internal_message_type());
  }
  if (!from._internal_host().empty()) {
    _this->_internal_set_host(from._internal_host());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RequestItems::CopyFrom(const RequestItems& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lite_monitor.RequestItems)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestItems::IsInitialized() const {
  return true;
}

void RequestItems::InternalSwap(RequestItems* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_type_, lhs_arena,
      &other->_impl_.message_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.host_, lhs_arena,
      &other->_impl_.host_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata RequestItems::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_request_5fitems_2eproto_getter, &descriptor_table_request_5fitems_2eproto_once,
      file_level_metadata_request_5fitems_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace lite_monitor
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::lite_monitor::RequestItems*
Arena::CreateMaybeMessage< ::lite_monitor::RequestItems >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lite_monitor::RequestItems >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
