// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response_items.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_response_5fitems_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_response_5fitems_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_response_5fitems_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_response_5fitems_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_response_5fitems_2eproto;
namespace lite_monitor {
class Item;
struct ItemDefaultTypeInternal;
extern ItemDefaultTypeInternal _Item_default_instance_;
class ResponseItems;
struct ResponseItemsDefaultTypeInternal;
extern ResponseItemsDefaultTypeInternal _ResponseItems_default_instance_;
}  // namespace lite_monitor
PROTOBUF_NAMESPACE_OPEN
template<> ::lite_monitor::Item* Arena::CreateMaybeMessage<::lite_monitor::Item>(Arena*);
template<> ::lite_monitor::ResponseItems* Arena::CreateMaybeMessage<::lite_monitor::ResponseItems>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace lite_monitor {

enum CollectType : int {
  UNKNOWN = 0,
  PREDEFINED = 1,
  USER_PARAMTER = 2,
  HTTP_AGENT = 3,
  CollectType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  CollectType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool CollectType_IsValid(int value);
constexpr CollectType CollectType_MIN = UNKNOWN;
constexpr CollectType CollectType_MAX = HTTP_AGENT;
constexpr int CollectType_ARRAYSIZE = CollectType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CollectType_descriptor();
template<typename T>
inline const std::string& CollectType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CollectType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CollectType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CollectType_descriptor(), enum_t_value);
}
inline bool CollectType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CollectType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CollectType>(
    CollectType_descriptor(), name, value);
}
// ===================================================================

class Item final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lite_monitor.Item) */ {
 public:
  inline Item() : Item(nullptr) {}
  ~Item() override;
  explicit PROTOBUF_CONSTEXPR Item(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Item(const Item& from);
  Item(Item&& from) noexcept
    : Item() {
    *this = ::std::move(from);
  }

  inline Item& operator=(const Item& from) {
    CopyFrom(from);
    return *this;
  }
  inline Item& operator=(Item&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Item& default_instance() {
    return *internal_default_instance();
  }
  static inline const Item* internal_default_instance() {
    return reinterpret_cast<const Item*>(
               &_Item_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Item& a, Item& b) {
    a.Swap(&b);
  }
  inline void Swap(Item* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Item* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Item* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Item>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Item& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Item& from) {
    Item::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Item* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lite_monitor.Item";
  }
  protected:
  explicit Item(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kDataTypeFieldNumber = 2,
    kCollectTypeFieldNumber = 3,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string data_type = 2;
  void clear_data_type();
  const std::string& data_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data_type();
  PROTOBUF_NODISCARD std::string* release_data_type();
  void set_allocated_data_type(std::string* data_type);
  private:
  const std::string& _internal_data_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data_type(const std::string& value);
  std::string* _internal_mutable_data_type();
  public:

  // .lite_monitor.CollectType collect_type = 3;
  void clear_collect_type();
  ::lite_monitor::CollectType collect_type() const;
  void set_collect_type(::lite_monitor::CollectType value);
  private:
  ::lite_monitor::CollectType _internal_collect_type() const;
  void _internal_set_collect_type(::lite_monitor::CollectType value);
  public:

  // @@protoc_insertion_point(class_scope:lite_monitor.Item)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_type_;
    int collect_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_response_5fitems_2eproto;
};
// -------------------------------------------------------------------

class ResponseItems final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lite_monitor.ResponseItems) */ {
 public:
  inline ResponseItems() : ResponseItems(nullptr) {}
  ~ResponseItems() override;
  explicit PROTOBUF_CONSTEXPR ResponseItems(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ResponseItems(const ResponseItems& from);
  ResponseItems(ResponseItems&& from) noexcept
    : ResponseItems() {
    *this = ::std::move(from);
  }

  inline ResponseItems& operator=(const ResponseItems& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResponseItems& operator=(ResponseItems&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResponseItems& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResponseItems* internal_default_instance() {
    return reinterpret_cast<const ResponseItems*>(
               &_ResponseItems_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ResponseItems& a, ResponseItems& b) {
    a.Swap(&b);
  }
  inline void Swap(ResponseItems* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResponseItems* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResponseItems* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ResponseItems>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ResponseItems& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ResponseItems& from) {
    ResponseItems::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResponseItems* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lite_monitor.ResponseItems";
  }
  protected:
  explicit ResponseItems(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemsFieldNumber = 2,
    kMessageTypeFieldNumber = 1,
  };
  // repeated .lite_monitor.Item items = 2;
  int items_size() const;
  private:
  int _internal_items_size() const;
  public:
  void clear_items();
  ::lite_monitor::Item* mutable_items(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lite_monitor::Item >*
      mutable_items();
  private:
  const ::lite_monitor::Item& _internal_items(int index) const;
  ::lite_monitor::Item* _internal_add_items();
  public:
  const ::lite_monitor::Item& items(int index) const;
  ::lite_monitor::Item* add_items();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lite_monitor::Item >&
      items() const;

  // string message_type = 1;
  void clear_message_type();
  const std::string& message_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message_type();
  PROTOBUF_NODISCARD std::string* release_message_type();
  void set_allocated_message_type(std::string* message_type);
  private:
  const std::string& _internal_message_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message_type(const std::string& value);
  std::string* _internal_mutable_message_type();
  public:

  // @@protoc_insertion_point(class_scope:lite_monitor.ResponseItems)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lite_monitor::Item > items_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_response_5fitems_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Item

// string name = 1;
inline void Item::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Item::name() const {
  // @@protoc_insertion_point(field_get:lite_monitor.Item.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Item::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lite_monitor.Item.name)
}
inline std::string* Item::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:lite_monitor.Item.name)
  return _s;
}
inline const std::string& Item::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Item::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Item::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Item::release_name() {
  // @@protoc_insertion_point(field_release:lite_monitor.Item.name)
  return _impl_.name_.Release();
}
inline void Item::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lite_monitor.Item.name)
}

// string data_type = 2;
inline void Item::clear_data_type() {
  _impl_.data_type_.ClearToEmpty();
}
inline const std::string& Item::data_type() const {
  // @@protoc_insertion_point(field_get:lite_monitor.Item.data_type)
  return _internal_data_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Item::set_data_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lite_monitor.Item.data_type)
}
inline std::string* Item::mutable_data_type() {
  std::string* _s = _internal_mutable_data_type();
  // @@protoc_insertion_point(field_mutable:lite_monitor.Item.data_type)
  return _s;
}
inline const std::string& Item::_internal_data_type() const {
  return _impl_.data_type_.Get();
}
inline void Item::_internal_set_data_type(const std::string& value) {
  
  _impl_.data_type_.Set(value, GetArenaForAllocation());
}
inline std::string* Item::_internal_mutable_data_type() {
  
  return _impl_.data_type_.Mutable(GetArenaForAllocation());
}
inline std::string* Item::release_data_type() {
  // @@protoc_insertion_point(field_release:lite_monitor.Item.data_type)
  return _impl_.data_type_.Release();
}
inline void Item::set_allocated_data_type(std::string* data_type) {
  if (data_type != nullptr) {
    
  } else {
    
  }
  _impl_.data_type_.SetAllocated(data_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_type_.IsDefault()) {
    _impl_.data_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lite_monitor.Item.data_type)
}

// .lite_monitor.CollectType collect_type = 3;
inline void Item::clear_collect_type() {
  _impl_.collect_type_ = 0;
}
inline ::lite_monitor::CollectType Item::_internal_collect_type() const {
  return static_cast< ::lite_monitor::CollectType >(_impl_.collect_type_);
}
inline ::lite_monitor::CollectType Item::collect_type() const {
  // @@protoc_insertion_point(field_get:lite_monitor.Item.collect_type)
  return _internal_collect_type();
}
inline void Item::_internal_set_collect_type(::lite_monitor::CollectType value) {
  
  _impl_.collect_type_ = value;
}
inline void Item::set_collect_type(::lite_monitor::CollectType value) {
  _internal_set_collect_type(value);
  // @@protoc_insertion_point(field_set:lite_monitor.Item.collect_type)
}

// -------------------------------------------------------------------

// ResponseItems

// string message_type = 1;
inline void ResponseItems::clear_message_type() {
  _impl_.message_type_.ClearToEmpty();
}
inline const std::string& ResponseItems::message_type() const {
  // @@protoc_insertion_point(field_get:lite_monitor.ResponseItems.message_type)
  return _internal_message_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ResponseItems::set_message_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lite_monitor.ResponseItems.message_type)
}
inline std::string* ResponseItems::mutable_message_type() {
  std::string* _s = _internal_mutable_message_type();
  // @@protoc_insertion_point(field_mutable:lite_monitor.ResponseItems.message_type)
  return _s;
}
inline const std::string& ResponseItems::_internal_message_type() const {
  return _impl_.message_type_.Get();
}
inline void ResponseItems::_internal_set_message_type(const std::string& value) {
  
  _impl_.message_type_.Set(value, GetArenaForAllocation());
}
inline std::string* ResponseItems::_internal_mutable_message_type() {
  
  return _impl_.message_type_.Mutable(GetArenaForAllocation());
}
inline std::string* ResponseItems::release_message_type() {
  // @@protoc_insertion_point(field_release:lite_monitor.ResponseItems.message_type)
  return _impl_.message_type_.Release();
}
inline void ResponseItems::set_allocated_message_type(std::string* message_type) {
  if (message_type != nullptr) {
    
  } else {
    
  }
  _impl_.message_type_.SetAllocated(message_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_type_.IsDefault()) {
    _impl_.message_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lite_monitor.ResponseItems.message_type)
}

// repeated .lite_monitor.Item items = 2;
inline int ResponseItems::_internal_items_size() const {
  return _impl_.items_.size();
}
inline int ResponseItems::items_size() const {
  return _internal_items_size();
}
inline void ResponseItems::clear_items() {
  _impl_.items_.Clear();
}
inline ::lite_monitor::Item* ResponseItems::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:lite_monitor.ResponseItems.items)
  return _impl_.items_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lite_monitor::Item >*
ResponseItems::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:lite_monitor.ResponseItems.items)
  return &_impl_.items_;
}
inline const ::lite_monitor::Item& ResponseItems::_internal_items(int index) const {
  return _impl_.items_.Get(index);
}
inline const ::lite_monitor::Item& ResponseItems::items(int index) const {
  // @@protoc_insertion_point(field_get:lite_monitor.ResponseItems.items)
  return _internal_items(index);
}
inline ::lite_monitor::Item* ResponseItems::_internal_add_items() {
  return _impl_.items_.Add();
}
inline ::lite_monitor::Item* ResponseItems::add_items() {
  ::lite_monitor::Item* _add = _internal_add_items();
  // @@protoc_insertion_point(field_add:lite_monitor.ResponseItems.items)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lite_monitor::Item >&
ResponseItems::items() const {
  // @@protoc_insertion_point(field_list:lite_monitor.ResponseItems.items)
  return _impl_.items_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace lite_monitor

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::lite_monitor::CollectType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::lite_monitor::CollectType>() {
  return ::lite_monitor::CollectType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_response_5fitems_2eproto
